// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Headbar from "@/components/Headbar";
// import Headbar2 from "@/components/Headbar2";

// import Bottombar from "@/components/Bottombar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Headbar2 className='headbar'/>
//         {children}
//         <Bottombar className='bottombar' />
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headbar2 from "@/components/Headbar2";
import Bottombar from "@/components/Bottombar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full`}
      >
        <Headbar2 />
        <main className="flex-1 overflow-y-auto">
          {children}
        </main>
        <Bottombar />
      </body>
    </html>
  );
}